# Generated by Django 4.0.3 on 2022-03-17 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OWLClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('label', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='OWLFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('file', models.FileField(upload_to='owls/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_change', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ontology',
                'verbose_name_plural': 'Ontologies',
            },
        ),
        migrations.CreateModel(
            name='OWLInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('owl_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.owlclass')),
            ],
            options={
                'verbose_name': 'Instance',
                'verbose_name_plural': 'Instances',
                'unique_together': {('owl_class', 'name')},
            },
        ),
        migrations.CreateModel(
            name='OWLRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('owl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.owlfile')),
            ],
            options={
                'verbose_name': 'Relationship',
                'verbose_name_plural': 'Relationships',
            },
        ),
        migrations.CreateModel(
            name='OWLRelationshipInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_causal', models.BooleanField(default=False)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_instance', to='api.owlinstance')),
                ('owlfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.owlfile')),
                ('relation_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_instance', to='api.owlinstance')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.owlrelationship')),
            ],
            options={
                'verbose_name': 'Relationship Instance',
                'verbose_name_plural': 'Relationship Instances',
            },
        ),
        migrations.AddField(
            model_name='owlclass',
            name='owl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.owlfile'),
        ),
        migrations.AlterUniqueTogether(
            name='owlclass',
            unique_together={('owl', 'name')},
        ),
    ]
